### ISSUE TITLE
Profiles are missing?

### ISSUE THREAD

**Issue by DragonQ** [rsiebert/TVHClient#351] opened 2018-08-20 20:21 UTC
I'm using Tvheadend 4.3 (unstable branch) because version 4.2 doesn't allow stream profiles with custom pipes. I have made a custom profile but it doesn't appear on the list of selectable profiles within TVHClient.

See this post for screenshots of what I mean:

[](https://tvheadend.org/boards/5/topics/33837?r=33855#message-33855)

Is this a bug?

**Comment by rsiebert** [comment] 2018-09-07 13:15
Hi can you provide the screenshot please.

**Comment by DragonQ** [comment] 2018-09-07 13:28
![ffmpeg-test-android-screenshot](https://user-images.githubusercontent.com/3251396/45221731-41079300-b2aa-11e8-94b9-f055e34e1424.png)
![ffmpeg-test-tvh-screenshot](https://user-images.githubusercontent.com/3251396/45221738-44028380-b2aa-11e8-9fe9-4ef4e3b0272a.png)

**Comment by rsiebert** [comment] 2018-09-07 13:30
Hmm, this should show up. So the server is not providing the information to the app. Maybe asking someone in the tvheadend forum could help?

**Comment by francoism90** [comment] 2018-09-11 07:49
@DragonQ Could you tell me more about the command line your are using? It looks like a lot more is possible. :)

Did you also select this profile in the user options? Depending on your setup, it may be needed to check some boxes to show non-default ones.

**Comment by DragonQ** [comment] 2018-09-11 09:33
The command line is just an ffmpeg encode. I know that regardless of what I put in the "command line" box, Tvheadend just errors when attempting to run it, but that's a totally separate Tvheadend issue. Note that the "audio", "matroska" and "pass" profiles are also missing from the TVHClient list.

I had a look in the TVHClient settings but couldn't find anything that looked relevant. Where do you think I need to check some options?

**Comment by rsiebert** [comment] 2018-09-14 18:52
When the app has connected to the server it makes a call to get the dvr and playback profiles. According to https://tvheadend.org/projects/tvheadend/wiki/Htsp these are getProfiles and getDvrConfigs. The lists that are returned are then shown in the settings. If the server does not list yours then I don't really know where to look.

**Comment by DragonQ** [comment] 2018-09-14 23:23
As I understand it, these profiles are not HTSP-based. However, this thread suggests that TVHClient _can_ see MPEG-TS spawn profiles:

https://tvheadend.org/boards/14/topics/28860

So I have no idea what's going on. It's not just MPEG-TS spawn profiles that are missing either: "matroska" for example doesn't show up either. I tried completely uninstalling the app, reinstalling it, clearing cache data, but it still only shows those 5 profiles.

**Comment by francoism90** [comment] 2018-09-15 08:01
@DragonQ This is what I meant: https://imgur.com/a/ix7XvQ2

**Comment by DragonQ** [comment] 2018-09-15 11:59
> @DragonQ This is what I meant: https://imgur.com/a/ix7XvQ2

Ah right. I tried changing that setting so that my profile would be visible but it still isn't:

![streaming profiles setting](https://user-images.githubusercontent.com/3251396/45585995-11c6d680-b8e7-11e8-9eec-afbb7a2b0383.png)

![tvhclient profiles](https://user-images.githubusercontent.com/3251396/45585998-1ab7a800-b8e7-11e8-8f99-60ec9563cd2b.png)

**Comment by rsiebert** [comment] 2018-10-10 15:24
Duplicate of #361

**Closed as completed** 2018-10-10 15:24 UTC
Labels: duplicate
