### ISSUE TITLE
Option to select multiple recordings for deletion

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#444] opened 2019-04-02 01:59 UTC
When deleting my multiple recordings at the moment it's a lot of selecting/confirming. I'd prefer a long tap to enable multi-select and then short tap on all recordings that are supposed to be selected for deletion.

**Comment by rsiebert** [comment] 2019-04-02 18:50
Duplicate of #314

**Comment by Flole998** [comment] 2019-05-15 22:25
When this is added please also add mass-deactivate and mass-activate feature, should be very very similar.

**Comment by rsiebert** [comment] 2019-05-21 18:57
Currently long pressing on a recording opens a popup menu. How should this be shown when long pressing shall enable multi select?

**Comment by Flole998** [comment] 2019-05-21 19:04
Seperate buttons at the top for enable/disable selected could be an option.

**Comment by rsiebert** [comment] 2022-06-27 20:21
Sorry, no time to implement this feaure

**Closed as completed by rsiebert** 2022-06-27 20:21 UTC
Labels: enhancement, question, ui
