### ISSUE TITLE
Wrong display of programm in program overview/DB Problem?

### ISSUE THREAD

**Issue by hgschehl** [rsiebert/TVHClient#371] opened 2018-09-30 10:28 UTC
Hi!

Pls. look in the attached screenshots at SAT1:
Harry Potter finishes at 17:41, followed by "Das große Backen" (2nd Screenshot). Both are displayed twice - which is wrong.
"Backen" should already be on 1st screenshot at the right for 19 min. and shoukd end middle of 2nd screenshot at 19:57, followed by "SAT1 Nachrichten", which is missing, followed by "Fuck ju Göthe" from 20:15 on.

Showing EPG-Data of SAT 1 showed double entries for Harry Potter and Backen with 1 min. difference (!! unfortunately without screenshot ...) [there's another minor issue: see date & time in screenshot 3...]

Deleting and reloading EPG-Data corrected then problem.

HG

![screenshot_20180930-120433_tvhclient](https://user-images.githubusercontent.com/38541939/46256473-d6620580-c4ab-11e8-85bd-8eac7f04f582.jpg)

![screenshot_20180930-120516_tvhclient](https://user-images.githubusercontent.com/38541939/46256476-dcf07d00-c4ab-11e8-970d-f9cdddf34157.jpg)

![screenshot_20180930-122127_tvhclient](https://user-images.githubusercontent.com/38541939/46256480-dfeb6d80-c4ab-11e8-8ff7-7142c5d728ad.jpg)

**Comment by rsiebert** [comment] 2018-10-02 09:57
The third issue (overlapping text) has been solved.
The others (duplicate entries) are known and are under investigation.

**Comment by rsiebert** [comment] 2019-04-24 08:31
Closing due to duplicate of #418

**Closed as completed by rsiebert** 2019-04-24 08:31 UTC
Labels: bug, ui
