### ISSUE TITLE
Server Crash on Manual Recording Edit

### ISSUE THREAD

**Issue by Andulien** [rsiebert/TVHClient#335] opened 2018-02-18 14:19 UTC
Problem:
1. Go to the App
2. Planned Recordings
3. Add a new Recording via the + sign with the default channel.
4. add some infos title, time etc.
5. save
6. Select the just created planned Recording
7. Select edit
8. Change the Channel
9. Save
10. tvheadend Server crashes.

Simply put when I edit the channel on a self created recording my tvheadend Server crashes. I have not tried if this is generally when you edit a recording or just when the channel ist changed, because it always takes some time to get the server up and running again with the configs etc.

tvheadend Server API Version32 - 4.4.20180208
Server: Synology DS212j DSM 6.1.5-15254
App: 1.9.12 (100)

**Comment by rsiebert** [comment] 2018-10-16 18:38
Is this still an issue? Sounds like a server bug to me.
I can't reproduce this on my server.

**Comment by Andulien** [comment] 2018-11-01 21:46
Can't test it anymore, since I had to reset my phone, and after reinstalling the Beta Version, I don't seem to have the full version anymore. I'll need to have a look at it later again, since right now the buying screen doesn't seem to load in the beta version, so I am not able to get the full version again at the moment.

**Comment by rsiebert** [comment] 2018-11-07 21:07
If the unlocker screen does not get loaded than this is a bug. Or does the purchase dialog show up and then nothing happens?

**Comment by rsiebert** [comment] 2018-11-16 08:49
I can't reproduce this on the 2.0.0 version, so I close the issue for now.

**Closed as completed by rsiebert** 2018-11-16 08:49 UTC
Labels: question
