### ISSUE TITLE
Can not cast any channel (malformed URL send to Chromecast)

### ISSUE THREAD

**Issue by WildPenquin** [rsiebert/TVHClient#532] opened 2021-05-25 17:23 UTC
Hi, 

I can not cast any channels. This used to work previously, but I seldomly actually use the software as I watch little TV. So I can not say when it broke.

Compared to previous log entries back from when it used to work, the URLs TVHClient is sending to chromecast are malformed. They look like this:

```
[C:ExternalPlayerViewModel] [M:getServerUrl] [L:150] [C:ConvertHostnameToAddressTask] [M:invoke] [L:16]   Original url was http://192.168.66.3:9981, converted url is http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@eeae9b:9981
doInBackground
[C:CastChannelActivity] [M:onTicketReceived] [L:51]  Cast channel from server with url http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@eeae9b:9981/stream/channelid/1035139682?ticket=4110809d92a32a74046b6c79b696f9033eae664c&profile=cast
[C:CastRemoteMediaClientCallback] [M:onSendingRemoteMediaRequest] [L:27]  onSendingRemoteMediaRequest
[C:CastChannelActivity$onTicketReceived] [M:onSendingRemoteMediaRequest] [L:77]  Sending remote media request
```
Any ideas as of to cause?

**Comment by WildPenquin** [comment] 2021-05-25 17:24
Attaching a log. **EDIT: ** Removed old log file and uploaded a shorter one after starting fresh on the Android phone. Cast URL:s still malformed:

**EDIT:** Replaced log again. Previous log had confusing "myserver" -entries. I'm not sure where that came from, I'm certain I've canged the hostname correctly. The URLs were still malformed (save for the weird hostname). Changed the log snippet, too.

```
[C:ConvertHostnameToAddressTask] [M:invoke] [L:14]  onPreExecute
[C:ExternalPlayerViewModel] [M:getServerUrl] [L:150]  Original url was http://arkkiville:9981, converted url is http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@f4b826a:9981
[C:CastChannelActivity] [M:onTicketReceived] [L:51]  Cast channel from server with url http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@f4b826a:9981/stream/channelid/1797598004?ticket=13f9200348fcf9af4ae071116d799ded4a11fe9e&profile=cast
[C:ConvertHostnameToAddressTask] [M:invoke] [L:16]  doInBackground
```


(FWIW I can play locally on the phone running TVHClient ...)

[tvhclient_2.4.6_234_25.05.2021 (8).log](https://github.com/rsiebert/TVHClient/files/6541263/tvhclient_2.4.6_234_25.05.2021.8.log)

**Comment by mario-tux** [comment] 2021-06-18 09:09
I got the same behavior: it is really `http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@f4b826a:9981/stream/cha...` the sent url?! It looks a bug in the conversion.

**Comment by ratenfanger** [comment] 2021-06-18 14:08
I'm also having trouble casting from inside the TVHClient app. Casting through VLC is working (see below). Full steps to reproduce:

1. Open TVHClient
2. Enable cast by selecting a cast destination (in my situation a Chromecast with AndroidTV called Woonkamer)
3. The television is now showing the TVHClient cast screen 
4. Open a channel and hit Cast
5. Now two things happens:
    1. TVHClient switches to the internal player which says "Casting to Woonkamer", this screen closes in about a second and TVHClient is back to the channel overview. There is no message displayed.
    2. The televion switches to a screen with play progress bar. This screen also closes in about a second without a message. It returns back to the TVHClient text.
6. Message in the logs is like the ones shown above.
```
[C:ExternalPlayerViewModel$requestTicketFromServer] [M:handleResponse] [L:117]  Received response for ticket request, path is /stream/channelid/1438758799, ticket is 4aed1846f6add468a01b8c563877aa1cc383bf9a
[C:BasePlaybackActivity$onCreate] [M:onChanged] [L:49]  Received ticket true
[C:ExternalPlayerViewModel] [M:getServerUrl] [L:130]  Convert hostname 192.168.1.50 to IP address
[C:ConvertHostnameToAddressTask] [M:invoke] [L:14]  onPreExecute
[C:ConvertHostnameToAddressTask] [M:invoke] [L:16]  [C:ExternalPlayerViewModel] [M:getServerUrl] [L:150] doInBackground
 Original url was http://192.168.1.50:9981, converted url is http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@28decff:9981
[C:CastChannelActivity] [M:onTicketReceived] [L:51]  Cast channel from server with url http://org.tvheadend.tvhclient.ui.features.playback.external.ConvertHostnameToAddressTask@28decff:9981/stream/channelid/1438758799?ticket=4aed1846f6add468a01b8c563877aa1cc383bf9a&profile=pass
[C:CastRemoteMediaClientCallback] [M:onSendingRemoteMediaRequest] [L:27]  onSendingRemoteMediaRequest
[C:CastChannelActivity$onTicketReceived] [M:onSendingRemoteMediaRequest] [L:77]  Sending remote media request
[C:ConvertHostnameToAddressTask] [M:invoke] [L:25]  onPostExecute
``` 

I can confirm that casting is working and correctly setup by casting through VLC:
1. Open TVHClient
2. Open a channel and hit play, choose VLC as application
3. The program now plays in VLC. Now hit cast to cast to the televion
4. VLC is now sucesfully casting the channel to the televion.

Environment:
- Phone: Galaxy S10e
- Android version: 11
- TVHClient version: 2.4.6 (234)
- TVHeadend version: latest build from Git (`4.3.0~pre+202106121356-0~built202106130418~giteb59284b8~ubuntu20.04.1` as provided by the [tvheadend-git PPA](https://launchpad.net/~mamarley/+archive/ubuntu/tvheadend-git))
- Playback URL: the problems happens when using an IP address and with a (globally) resolvable DNS name as plackback URL.
- Cast profile: pass, I can confirm this is working because it works when using cast through VLC. The Chromecast with AndroidTV does support H265 :).

@rsiebert Can we do anything to help you resolving this issue? I have a externally accesible TVHeadend installation if you need one :)

**Comment by ratenfanger** [comment] 2021-06-18 14:35
I took a little dive in the code and it looks like commit 21fe2050178928b192b5b9af167d216b7fe1c8b7 and 8349d3104a06d89493d0adc29b85d06fe1c63f9e don't play well together. In the ExternalPlayerViewModel the object hash of the ConvertHostnameToAddressTask instance is returned instead of the result of the executeAsyncTask. Unfortunately I don't have enough Kotlin experience to help you out with this problem, but maybe I can help you with testing when you found some time to fix this?

**Comment by rsiebert** [comment] 2021-09-11 19:37
Hi, can you test this version? 2.4.7-235. (I had to remove the link here. google has rejected the release of the app in the playstore due to policy violations)

**Comment by ratenfanger** [comment] 2021-09-12 10:10
Hi @rsiebert, I was just typing a response that 2.4.7-234 has the same problem when I saw that you added a new version, 235. I tried it immediately and it works flawlessly! Thank you very much for fixing it! 👌

**Comment by rsiebert** [comment] 2021-09-12 18:56
Ok, then I'll prepare a release.

**Comment by rsiebert** [comment] 2022-01-04 21:29
The new release will contain the bugfix. Unfortunately my app was not released because google blocked it due to some false policy violation issue. It was resolved few days ago I hope that the app update will be available soon.

**Comment by rsiebert** [comment] 2022-06-27 19:57
Version 2.4.7 was released a while ago.

**Closed as completed by rsiebert** 2022-06-27 19:57 UTC
Labels: bug
