### ISSUE TITLE
Beta v2: only available profile for playback is "None"

### ISSUE THREAD

**Issue by pejobo** [rsiebert/TVHClient#356] opened 2018-09-19 17:38 UTC
App version is 2.0.0 (104)
I cannot choose a playback profile (only option is "None").
And when trying to start playback I get the "error_starting_playback_no_profile" message.
TVHeadend sever is reported as 4.2.3 and api version 27 (it's not an official release but self-compiled from git).
Available (=enabled) profiles in web view are "audio", "htsp", and "pass" (latter is the default profile). There are other profiles, which are not enabled. Recording profiles available in the app are "None" and "Default profile".

**Comment by francoism90** [comment] 2018-10-06 18:35
I'm able to select `htsp`, the webtv-*` profiles and my custom cast on beta v2 (today's build)

**Comment by rsiebert** [comment] 2018-10-10 15:41
Duplicate of #361

**Closed as completed** 2018-10-10 15:41 UTC
Labels: duplicate
