### ISSUE TITLE
The "back" button always closes the app, when used after a search operation in finished recordings on a tablett

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#484] opened 2019-12-06 14:23 UTC
The "back" button always closes the app, when used after a search operation in finished recordings on a tablett. This does not happen on a phone.

**Comment by vzsze** [comment] 2019-12-06 14:52
Here's a logfile.

[tvclient_2.3.1_190_06-12-2019.log](https://github.com/rsiebert/TVHClient/files/3932695/tvclient_2.3.1_190_06-12-2019.log)

**Comment by rsiebert** [comment] 2020-01-06 18:38
Please try the 2.3.4 version. There I can't reproduce the issue.
Closing for now.

**Closed as completed by rsiebert** 2020-01-06 18:38 UTC
Labels: invalid, ui
