### ISSUE TITLE
Can not cast recordings

### ISSUE THREAD

**Issue by WildPenquin** [rsiebert/TVHClient#465] opened 2019-08-05 20:57 UTC
Hi!

I have set casting profiles in tvheadend as suggested in the Wiki: https://github.com/rsiebert/TVHClient/wiki/Using-Google-Chromecast.

I can cast Live TV shows without any issues.

However, I can not cast any recordings. Trying to do so will briefly display the description of the recording via ChromeCast and then revert back to just the big "TVHClient" text.

TVheadend I'm running is version 4.3-1804~gebb096804-dirty, on an Arch Linux server.

**Comment by rsiebert** [comment] 2019-08-10 20:53
Please send me a debug log. 
Is the server transcoding the recordings properly? Is the format supported for transcoding?

**Comment by rsiebert** [comment] 2019-08-16 09:24
I guess the issue is related to #471

**Comment by rsiebert** [comment] 2019-08-20 10:48
I'm closing the issue. If the issue remains feel free to reopen.

**Closed as completed by rsiebert** 2019-08-20 10:48 UTC
Labels: bug, duplicate

**Comment by WildPenquin** [comment] 2019-08-23 20:04
Hi!

No, the issue still persists (sorry I didn't reply earlier - I have been travelling).

I have (and had) set all profiles to "cast" in TVHClient (on the Android phone).

Here is a log file, where I once play a live channel and then try to play a recording. Actually, I first play the live channel with an external player (succesfully) and then cast (succesfully). Then I play the recording in an external player (succesfully, although "Pictures" program can not play any audio) and then try to cast (and this fails).:

[tvhclient_2.2.21_182_23.08.2019.log](https://github.com/rsiebert/TVHClient/files/3536025/tvhclient_2.2.21_182_23.08.2019.log)
