### ISSUE TITLE
I Title or Subtitle contains a ?, the downloading filename extension is not created

### ISSUE THREAD

**Issue by vzsze** [rsiebert/TVHClient#481] opened 2019-10-29 14:26 UTC
When the download-filename contains a ? at the end, the filename extension (like mkv) is not appended. This results in an error message when trying to play that file on Android. 

This bug is related to #479

**Comment by rsiebert** [comment] 2019-10-29 19:06
Are there any other special characters that might occur?

**Comment by vzsze** [comment] 2019-10-30 12:53
At least /\:*"?<>| should be avoided.

**Comment by rsiebert** [comment] 2019-11-18 21:12
Here is a new upcoming test version [2.3.0](https://drive.google.com/open?id=1oHT6Tv8UicnsFkvGLAzJHnkWFZ87J7P5). Can you check if the filename stuff works?

**Comment by vzsze** [comment] 2019-11-22 09:54
The file system stuff works ok. "?" and "/" are replaced, but I noticed, that the "back" button always closes the app, when used after a search operation in finished recordings.

**Comment by rsiebert** [comment] 2019-12-06 12:42
Hmm, I cant reproduce the back button issue here with 2.3.0 or 2.3.1 using a smartphone. Using the back button shows the list with the finished recordings again. Any other clues?

**Comment by rsiebert** [comment] 2019-12-06 13:08
2.3.1 was just released, so I'll close this issue.
Please open a new ticket to keep track of the back button issue

**Closed as completed by rsiebert** 2019-12-06 13:08 UTC
Labels: bug, done

**Comment by vzsze** [comment] 2019-12-06 14:13
You are right. On my phone that doesn't happen either, but it still happens on my tablett. I'll open a bug for that.
