### ISSUE TITLE
Series Link Functionality Broken? (UK)

### ISSUE THREAD

**Issue by Adam1986** [rsiebert/TVHClient#337] opened 2018-03-05 15:02 UTC
Hello,

Relatively new to the world of TVHeadend after switching over from MediaPortal completely so I don't know if there is any additional logging from the client or the server that can be provided to assist with this.

Basically series link recording does not appear to work as expected.  A good example is enabling Masterchef on BBC One HD for Series record.  It appears to schedule up anything relating to Masterchef.

The live logs show like this on the tvheadend server:

> 2018-03-05 14:55:54.018 dvr: entry 73da53fe308f0dafa26517755337786d "MasterChef Australia" on "Home" starting at 2018-03-05 18:54:30, with broadcast id "crid://bds.tv/DSEN5J", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.018 dvr: entry 70905d8708ddf76e41a7198ee847dec4 "MasterChef Australia" on "Home" starting at 2018-03-06 09:54:30, with broadcast id "crid://bds.tv/DSEN5N", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.018 dvr: entry 118abe12fb800808178b99cdb7a8cd7e "MasterChef Australia" on "Home" starting at 2018-03-07 09:54:30, with broadcast id "crid://bds.tv/DSEN5P", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.018 dvr: entry 3762e625905d229d719210888bfbd1fd "MasterChef Australia" on "Home" starting at 2018-03-08 09:54:30, with broadcast id "crid://bds.tv/DSEN5R", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.018 dvr: entry dc8639b64c9c6f3a4ebb7abb208c68f9 "MasterChef Australia" on "Home" starting at 2018-03-09 09:54:30, with broadcast id "crid://bds.tv/DSEN5T", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.019 dvr: entry 0cb4093e3bf30251cc7f95dc14a47c2d "MasterChef Australia" on "Home" starting at 2018-03-12 09:54:30, with broadcast id "crid://bds.tv/DSEN5Z", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.020 dvr: entry a431803d56d750a8cbce3a7ccfa6b0cc "MasterChef" on "BBC ONE Yorks" starting at 2018-03-05 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXI", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.020 dvr: entry 5fe82064d3000c0d4af8f850daae7dde "MasterChef" on "BBC ONE Yorks" starting at 2018-03-08 19:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXJ", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.020 dvr: entry 3ce86986034a6b5cebf1e7469715da8e "MasterChef" on "BBC ONE Yorks" starting at 2018-03-09 19:24:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXK", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.020 dvr: entry dca66f3240d7688647f72fe24620e1a5 "MasterChef" on "BBC ONE Yorks" starting at 2018-03-12 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXL", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.023 dvr: entry 584f3ec20abfdd0f44024e694682c399 "MasterChef Australia" on "Home" starting at 2018-03-05 18:54:30, with broadcast id "crid://bds.tv/DSEN5J", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.024 dvr: entry d1c63936546f669e0e32f48acb64e306 "MasterChef Australia" on "Home" starting at 2018-03-06 09:54:30, with broadcast id "crid://bds.tv/DSEN5N", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.024 dvr: entry 5ad1d9873dcad017b036d4b332dc699e "MasterChef Australia" on "Home" starting at 2018-03-07 09:54:30, with broadcast id "crid://bds.tv/DSEN5P", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.024 dvr: entry ffdc2ae335d5f2cd929c6b21af3d01a8 "MasterChef Australia" on "Home" starting at 2018-03-08 09:54:30, with broadcast id "crid://bds.tv/DSEN5R", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.024 dvr: entry 53682d6787ed24db142abb05457a4c00 "MasterChef Australia" on "Home" starting at 2018-03-09 09:54:30, with broadcast id "crid://bds.tv/DSEN5T", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.024 dvr: entry a6f81245b9f90b0abd5ddab9d5dac378 "MasterChef Australia" on "Home" starting at 2018-03-12 09:54:30, with broadcast id "crid://bds.tv/DSEN5Z", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.025 dvr: entry f5ca7c0e57a8e4afae0d055fa62c9d73 "MasterChef" on "BBC ONE Yorks" starting at 2018-03-05 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXI", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.025 dvr: entry 4c8f1aaf0e4533672aa9b99a7883f2f4 "MasterChef" on "BBC ONE Yorks" starting at 2018-03-08 19:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXJ", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.026 dvr: entry 2984e0c4b77fb84dee1c1a610cc142f9 "MasterChef" on "BBC ONE Yorks" starting at 2018-03-09 19:24:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXK", scheduled for recording by "kodi"
> 
> 2018-03-05 14:55:54.026 dvr: entry 82b48faf881bc3d1da573e21a5bfb4cb "MasterChef" on "BBC ONE Yorks" starting at 2018-03-12 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXL", scheduled for recording by "kodi"

However, if I schedule this up via another application such as Zapette, or within TVHeadend itself, it appears to work as expected:

> 2018-03-05 14:59:29.434 dvr: entry 6f9f3dbd4c9042dc91604042225e589b "MasterChef" on "BBC ONE HD" starting at 2018-03-05 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXI", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.434 dvr: entry 89a7cd3caa23e3faf3262ad0277a23a1 "MasterChef" on "BBC ONE HD" starting at 2018-03-08 19:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXJ", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.434 dvr: entry ff49132dde1edc07742fa856ffba7ba8 "MasterChef" on "BBC ONE HD" starting at 2018-03-09 19:24:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXK", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.434 dvr: entry 2eae241b6ba0695a360748b301d912a3 "MasterChef" on "BBC ONE HD" starting at 2018-03-12 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXL", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.436 dvr: entry 11349ccaf2d197c79f75bfc1fba2a8b1 "MasterChef" on "BBC ONE HD" starting at 2018-03-05 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXI", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.436 dvr: entry 0a6fed77e16cc17688c41ef0cf8a2382 "MasterChef" on "BBC ONE HD" starting at 2018-03-08 19:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXJ", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.436 dvr: entry 0101934865c748bb661f56eb50cf2e22 "MasterChef" on "BBC ONE HD" starting at 2018-03-09 19:24:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXK", scheduled for recording by "kodi"
> 
> 2018-03-05 14:59:29.436 dvr: entry 9e3bbcf8277966548e4892c6d01ca59a "MasterChef" on "BBC ONE HD" starting at 2018-03-12 20:54:30, with broadcast id "crid://fp.bbc.co.uk/1RKKXL", scheduled for recording by "kodi"
> 

Any idea what is causing this behaviour?

Thanks

**Comment by Adam1986** [comment] 2018-05-31 19:23
Just wondered if anyone could advise on this? This is still an issue unfortunately.

**Comment by Adam1986** [comment] 2018-10-05 19:51
This is still very much an issue even in the latest beta.  Please can you try and help with this?

**Comment by rsiebert** [comment] 2018-11-26 16:04
The htsp version change the handling of the series link. I'll add this.
Closing this as duplicate of #301.

**Closed as completed by rsiebert** 2018-11-26 16:04 UTC
