### ISSUE TITLE
Remove line under title : Language

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#197] opened 2015-12-30 12:11 UTC
Please remove line under Language to set as other menu without line and move check box option some pixel down. I show on screen.
![1](https://cloud.githubusercontent.com/assets/4134018/12050501/d319f59a-aef6-11e5-8727-4f6636bbc045.jpg)

After change
![2](https://cloud.githubusercontent.com/assets/4134018/12050505/d8e9a128-aef6-11e5-8d7e-47f2a040bb4a.jpg)

**Comment by rsiebert** [comment] 2015-12-31 08:56
This is not a bug of the app itself, but of the material-dialogs library I use. I'll gradually port the app use the google design libraries where this problem should be solved.

**Comment by ghost** [comment] 2015-12-31 11:27
Ok i am waiting...

**Comment by rsiebert** [comment] 2015-12-31 11:50
Ok, until then I'll close this issue.

Piotr Kuchciak notifications@github.com schrieb am Do., 31. Dez. 2015 um
12:27 Uhr:

**Closed as completed** 2015-12-31 11:50 UTC
