### ISSUE TITLE
What are the requirements if I want to use the internal player?

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#463] opened 2019-07-23 21:21 UTC
On my Sony Xperia Z2 Tablet the internal player is not working.
On my Google Pixel 2 I have video and audio on some channels only audio.

So I wonder if there are any requirements?

**Comment by rsiebert** [comment] 2019-07-24 11:36
Did you enable the setting to play live tv with the internal player? See settings -> playback.
The exoplayer can play the following formats: 
https://exoplayer.dev/supported-formats.html#progressive-container-formats
https://exoplayer.dev/supported-formats.html#ffmpeg-extension

Video formats like TS is not supported. But it can be changed in the servers webinterface that mkv (matroska) is used.

**Comment by AlBundy33** [comment] 2019-07-24 16:41
Seems that I haven't tried the internal player for a long time on my tablet.
Both devices have the same problems 
On HD channels (ARD, ZDF,...) I have audio and video but on SD (RTL, Pro7,...) I have only audio.

TVHeadend is set to use pass through because it runs on a raspberry pi 3.

**Comment by AlBundy33** [comment] 2019-07-24 16:49
Setting matroska as default streaming profile didn't help

**Comment by rsiebert** [comment] 2019-07-24 19:50
Can you test using the htsp profile? Did you also set the htsp profile in the playback settings?

**Comment by AlBundy33** [comment] 2019-07-24 20:43
Same problem.

![Screenshot_20190724-224108](https://user-images.githubusercontent.com/6294586/61827239-5eaefe00-ae64-11e9-96a7-b29aee665b4f.png)
![Screenshot_20190724-223926](https://user-images.githubusercontent.com/6294586/61827240-5eaefe00-ae64-11e9-903d-0a76007c2d10.png)

**Comment by rsiebert** [comment] 2019-07-24 21:54
Hmm, then please send me the debug log when starting playback. Maybe there are some hints.

**Comment by AlBundy33** [comment] 2019-07-24 22:06
[tvhclient_2.2.15_174_25.07.2019.log](https://github.com/rsiebert/TVHClient/files/3428914/tvhclient_2.2.15_174_25.07.2019.log)

**Comment by AlBundy33** [comment] 2019-07-25 20:09
According to MX Player Video Stream of ZDF HD (working) is H264 / AVC / MPEG-4 AVC / MPEG-4 part 10 and Vox (only audio) is MPEG-2

**Comment by AlBundy33** [comment] 2019-07-30 19:09
Is there any way to play mpeg-2 with the internal player?

**Comment by rsiebert** [comment] 2020-01-06 18:41
Any news on the topic with the 2.3.4 app version? Which android versions are your phone and tablet using?

**Comment by AlBundy33** [comment] 2020-01-06 21:09
Unfortunately not - I can watch HD channels but on SD channels I have only audio and no video.
I'm using Android 9 and 10.

**Comment by rsiebert** [comment] 2020-01-07 16:11
Here is an intermediate version [2.3.5](https://drive.google.com/open?id=16OG8jSp0ncbkUuC5KPeVm6gEsB6qjopP) of the app.
Please enable debug logging and start to play a stream. The used video and audio format should then be logged. Please send the log to me afterwards. This could help to see why SD channels can't be played.

**Comment by AlBundy33** [comment] 2020-01-07 17:54
Done.
I've started a SD channel until I've heard audio, then I've started a HD channel until I've seen video an then  I've started a SD channel again.

**Comment by rsiebert** [comment] 2020-01-07 19:37
When you're playing a SD channel I see the following:

- Track:0, selected=no, id=1, mimeType=video/mpeg2, res=720x576, fps=25.0, supported=no, unsupported type
- The audio type for the SD channels are mimeType=audio/mpeg-L2, which is supported.

Your HD streams are using the video type mimeType=video/avc, this is supported.

Thats why you have sounds but no video on SD channels.

**Comment by AlBundy33** [comment] 2020-01-07 19:51
so the internal player will never support video/mpeg2?

**Comment by rsiebert** [comment] 2020-01-10 08:52
Someone has started to implement a video decoder for mpeg2 video two or more years ago. But it was never finished and according to the exoplayer website support not planned. 
So unfortunately I would says yes: It will never be supported.
Is it possible to define a different transcoding profile on the server for SD channels?

Here is another intermediate version [2.3.5-198](https://drive.google.com/open?id=1y7scLqAXUl8Jjdp7H1uaBhjUiXsB4ZVf) with two minor changes regarding the mpeg2 stuff, but I strongly assume it will not change anything.

**Comment by AlBundy33** [comment] 2020-01-11 21:18
unfortunately still no video for sd channels. :-(
then I have to use an external player. :-(

**Comment by rsiebert** [comment] 2020-02-15 20:06
I'm closing this because this ticket is a duplicate of #411

**Closed as completed** 2020-02-15 20:06 UTC
Labels: duplicate
