### ISSUE TITLE
Wrong series created from program guide.

### ISSUE THREAD

**Issue by lloyda** [rsiebert/TVHClient#493] opened 2020-01-13 19:01 UTC
If I select an entry from the program guide and try and create a series recording, it often picks the wrong channel/time.  It is usually from a channel that is higher up in the display, and sometimes, but not always, at a later time - the next time slot so to speak.  It is not always wrong - it seems to go in phases.  Sometimes it is correct on every attempt, and then it will be wrong on a whole sequence.

**Comment by lloyda** [comment] 2020-01-13 19:24
I do wonder it the issue is related to how much scrolling I've done with the program guide.  It seems to be worse towards the bottom of the list.

**Comment by lloyda** [comment] 2020-01-15 13:33
Just spotted that this could be the same as issue #440

**Comment by Flole998** [comment] 2020-01-28 22:31
Sounds related to me. Try to scroll slower, that's the only solution at this point (and I know that it's impossible cause we're all super impatient ;) )

**Comment by lloyda** [comment] 2020-01-29 13:16
Speed of scrolling does not seem to affect this (and you don't need to scroll far).  I'll keep testing to see if I can come up with a pattern.

**Comment by Flole998** [comment] 2020-01-29 13:18
For me it happens whenever it hangs during scrolling, that only happens when I scroll fast. As mentioned in the other issue this is probably an issue with the library used.

**Comment by rsiebert** [comment] 2020-02-10 09:14
This issue is hard to reproduce. The scrolling and clicking behaviour is indeed controlled by the underlying android libraries.

**Comment by rsiebert** [comment] 2020-02-10 09:15
I am closing this because it is a duplicate of #440

**Closed as completed** 2020-02-10 09:16 UTC
Labels: duplicate
