### ISSUE TITLE
Programs displayed twice

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#395] opened 2018-11-18 20:13 UTC
See screenshot. 
I've seen this today after starting a recording from tvhclient of a currently running program. 

![screenshot_20181118-211049](https://user-images.githubusercontent.com/6294586/48677541-97c8fd00-eb76-11e8-954e-5f3527dc7bae.png)

**Comment by rsiebert** [comment] 2018-11-26 16:12
Closing this as duplicate of #371

**Closed as completed by rsiebert** 2018-11-26 16:12 UTC
Labels: bug
