### ISSUE TITLE
Privacy declaration on black theme written white on white background

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#468] opened 2019-08-13 22:05 UTC
When the black theme is active, changelog and privacy declaration are written in white letters on white background making it unreadable.

**Comment by rsiebert** [comment] 2019-08-14 08:20
![Changelog_black_theme](https://user-images.githubusercontent.com/1406960/63005466-e9d84e00-be7c-11e9-9995-90fffa77f1f2.png)
![Privacy_policy_black_theme](https://user-images.githubusercontent.com/1406960/63005483-f3fa4c80-be7c-11e9-9484-13c7b1f4de68.png)

I have attached two screenshots regarding this issue. I cannot reproduce it here. Anyone else having this issue?
What phone and android version do you have?

**Comment by Flole998** [comment] 2019-08-14 08:57
That happens just when it was opened at the start, not when being called from the settings. Also here the word "General" is cut. Android 9, OnePlus 3.

**Comment by rsiebert** [comment] 2019-08-14 16:28
this should be fixed in 2.2.20 which I have released on 14.8.2019 in the afternoon. Somehow its not yet available in the playstore

**Closed as completed** 2019-08-16 20:32 UTC
Labels: bug, done, ui
