### ISSUE TITLE
Play in external player fails

### ISSUE THREAD

**Issue by Ollo1** [rsiebert/TVHClient#302] opened 2017-06-12 19:20 UTC
Hello I have an issue playing a stream within an external player on my Galaxy TabS2. Usually it worked however it doesn't anymore. 
Access settings within TVheadend are verified and stream plays nicely on a PC using the same credential.

I have MXPlayer and Samsung Video Library (Video-Player) installed. After clicking play the Samsung player starts instead of MXPlayer which is set as sytem default player. I wouldn't care about this issue if it would play the stream but it doesn't. The only message I get sums up to device disconnected please reconnect to network.

Any idea I could force the MXPlayer to open the stream? I can't disable nor uninstall the Samsung due to missing root.

Attached you find a log if this might help.

[tvhclient_12.06.2017.txt](https://github.com/rsiebert/TVHClient/files/1069263/tvhclient_12.06.2017.txt)

**Comment by bentolor** [comment] 2017-06-21 19:24
Confirmed. Same here! 

Using MXPlayer to play TVHeadend stream. Launching "play channel" from TVHGuide works flawlessly. Launching from TVHGuide (same configuration) only shows a connection waiting loop.

**Comment by DirtBagXon** [comment] 2017-06-28 17:16
I believe since the upgrade to TVH v4.2 this has happened.

I now see the same issue in both MXPlayer and VLC, neither being able to stream channels or recordings. Where both were working perfectly before hand.

I suspect that the M3U that is being passed to the external player is getting messed up, or at least no longer possible to parse. 

MXplayer now reports 'Can't play this link'..... VLC just hangs......

**Comment by DirtBagXon** [comment] 2017-06-28 17:38
In fact this appears worse with MXPlayer, it would appear what is being passed to the external player is being misinterpreted...
 
With debug on:
1. I select VLC to play channel and it hits the server.
2. Select MXPlayer, I see no hit to the server -  'Can't play this link'
3. VLC..
4. MXPlayer...  'Can't play this link'

Below is debug log on the server.....

```
2017-06-28 18:29:17.275 http: 10.10.10.16: using ticket C43725A0926EF96B2E00EFAE2A55D6546C9D1C01 for /stream/channelid/1115647144
2017-06-28 18:29:17.276 subscription: 06F9: "HTTP" subscribing on channel "BBC ONE Lon", weight: 100, adapter: "DiBcom 7000PC : DVB-T #0", network: "Freeview", mux: "490MHz", service: "BBC ONE Lon", profile="pass", hostname="10.10.10.16", client="VLC/3.0.0-git LibVLC/3.0.0-git"
2017-06-28 18:29:23.260 subscription: 06F9: "HTTP" unsubscribing from "BBC ONE Lon", hostname="10.10.10.16", client="VLC/3.0.0-git LibVLC/3.0.0-git"
2017-06-28 18:31:31.770 http: 10.10.10.16: using ticket EC52C176E004AC019753186E30C0F1C43627F6E5 for /stream/channelid/1115647144
2017-06-28 18:31:31.770 subscription: 06FA: "HTTP" subscribing on channel "BBC ONE Lon", weight: 100, adapter: "DiBcom 7000PC : DVB-T #0", network: "Freeview", mux: "490MHz", service: "BBC ONE Lon", profile="pass", hostname="10.10.10.16", client="VLC/3.0.0-git LibVLC/3.0.0-git"
2017-06-28 18:31:35.285 subscription: 06FA: "HTTP" unsubscribing from "BBC ONE Lon", hostname="10.10.10.16", client="VLC/3.0.0-git LibVLC/3.0.0-git"
```

**Comment by rsiebert** [comment] 2017-09-06 11:33
Has this been fixed in the server or any other news on this issue?

**Comment by bentolor** [comment] 2017-09-06 11:45
@rsiebert Unchanged – not working. 

Why do you suspect this to be a server issue? Would rather guess it's an issue in the way how TVHClient passes the target URL to the player.

**Comment by rsiebert** [comment] 2017-09-06 12:19
Because the last TVHClient version 1.9.8 was released in 13.01.2017. This issue was created half a year later in June. The new version 1.9.9 has no changes in the playback code. Additionally the user DirtBagXon wrote on June 28th "I believe since the upgrade to TVH v4.2 this has happened."

**Comment by bentolor** [comment] 2017-09-06 12:27
Ok, fair enough. 

But while TVHClient fails, TVHGuide still works fine with MXPlayer using the same backend. That's why I'd suspect the client rather than the server.

**Comment by DirtBagXon** [comment] 2017-09-06 12:44
I do believe this is a change in the M3U being passed from the backend. I am still running v4.2.2 backend, but now VLC works flawlessly spawned from the 'Play' link in TVHClient - MXPlayer Pro still continuously gives the waiting loop and finally 'Can't play this link' error.

What is more puzzling is the fact I don't see the hit against tvheadend in debug mode when using MXplayer as the player. So the M3U is completely being mangled as to not attempt the external hit. 

So it would appear it could be an issue between TVHClient and MXPlayer, VLC seems to make sense of the same referrer though, perhaps through less stringent checks...

It there a means to debug what is being sent to the player within TVHClient debug?

**Comment by DirtBagXon** [comment] 2017-09-06 13:36
"TVHGuide still works fine with MXPlayer using the same backend" - my experience also.

I suspect that the backend may have had a format change, and perhaps TVHClient is not reformatting/tidying what is forwards correctly, and then it's left up to the player to interpret the new link. Some better than others obviously.....

Again debug of the link passed to the player, might shed some light....  It may be a MXPlayer issue but at the moment we don't have information to pass to MXPlayer devs....

**Comment by Ollo1** [comment] 2017-09-12 18:17
I'm sorry for the long abscence have been to long offline. 

With TVHClient version 1.9.9 I don't have the issue any longer. Using the launching option "play channel" from TVHGuide I was able to make MXPlayer the default player. Now streaming works fine independently if started from the guide, overview or records.
In my opinion this can be closed. By the way I have server version 4.4.20170707 running.

**Comment by rsiebert** [comment] 2017-09-12 19:49
Closing issue

**Closed as completed by rsiebert** 2017-09-12 19:49 UTC
Labels: question

**Comment by bentolor** [comment] 2017-09-29 18:54
I still had the same issue with TVHClient not working, but TVHGuide did. After a little research I resolved it as follows:

* Created a dedicated user `mkv` with password
* Changed TVHClient to use that user
* Revoked the HTSP Stream-Permission and force-assigned the `matroska`-Streamprofile for the new user `mkv`
